#!/usr/bin/env perl
#--------------------------------------------------------------------------
# 001-instance-status-check
#--------------------------------------------------------------------------
# Copyright(C) 2024-present Brett Estrade
# Copyright(C) 2024-present Jason Fleming
#
# This file is part of the ADCIRC Surge Guidance System (ASGS).
#--------------------------------------------------------------------------

use v5.12;
use strict;
use warnings;

use JSON::PP qw/decode_json encode_json/;
use Term::ANSIColor qw/colored/;

use constant {
    OK       => 0,
    WARNING  => 1,
    CRITICAL => 2,
    UNKNOWN  => 3,
    NOTIFY   => 4,
};

my ($oldout, $oldexit, $count, $delay, $profile, $configfile, $statefile, $verbose) = @ARGV;
$oldout    = $ENV{ASGS_MON_OLDOUT}  if exists $ENV{ASGS_MON_OLDOUT};
$oldexit   = $ENV{ASGS_MON_OLDEXIT} if exists $ENV{ASGS_MON_OLDEXIT};
$count     = $ENV{ASGS_MON_COUNT}    if exists $ENV{ASGS_MON_COUNT};
$delay     = $ENV{ASGS_MON_DELAY}    if exists $ENV{ASGS_MON_DELAY};
$profile   = $ENV{ASGS_MON_PROFILE}  if exists $ENV{ASGS_MON_PROFILE};
$configfile= $ENV{ASGS_MON_CONFIG}   if exists $ENV{ASGS_MON_CONFIG};
$statefile = $ENV{ASGS_MON_STATEFILE} if exists $ENV{ASGS_MON_STATEFILE};
$verbose   = $ENV{ASGS_MON_VERBOSE}  if exists $ENV{ASGS_MON_VERBOSE};

my $this = $0;
$this =~ s{.*/}{};
my $hpc  = $ENV{ASGS_MON_HPCENVSHORT} // $ENV{HPCENVSHORT} // q{unknown};
my $file = $ENV{ASGS_MON_INSTANCEFILE};
my $key  = q{time.status.lastupdated};

if (not defined $file or $file eq q{} or not -r $file) {
    print "($hpc $profile - $this) WARNING INSTANCEFILE is not readable\n\n";
    print "Expected: " . ($file // q{<undefined>}) . "\n";
    print "The file may not have been created yet, or ASGS may not be progressing normally.\n";
    exit WARNING;
}

my $data = eval {
    open my $fh, q{<}, $file or die "$!";
    local $/;
    my $json = <$fh>;
    close $fh;
    decode_json($json);
};

if (not $data or $@) {
    my $err = $@ || q{unknown JSON decode error};
    print "($hpc $profile - $this) WARNING INSTANCEFILE JSON is invalid\n\n";
    print "File: $file\n\n$err\n";
    exit WARNING;
}

my $value = $data->{$key};
my $newout = encode_json({ value => $value });

my $old;
if (defined $oldout and $oldout =~ /\A\s*\{/) {
    $old = eval { decode_json($oldout) };
}

if ($verbose) {
    if ($old && defined($old->{value}) && defined($value) && "$old->{value}" ne "$value") {
        print STDERR "($hpc " . colored($profile // q{}, q{cyan}) . " - "
            . colored($this, q{green}) . ") $key changed from $old->{value} to $value\n";
    }
    else {
        my $display = defined $value ? $value : q{<undefined>};
        print STDERR "($hpc " . colored($profile // q{}, q{cyan}) . " - "
            . colored($this, q{green}) . ") $key: $display\n";
    }
}

print $newout;
exit OK;
