#!/usr/bin/env bash
#--------------------------------------------------------------------------
# 003-syslog-progress
#--------------------------------------------------------------------------
# Copyright(C) 2024-present Brett Estrade
# Copyright(C) 2024-present Jason Fleming
#
# This file is part of the ADCIRC Surge Guidance System (ASGS).
#--------------------------------------------------------------------------

source "${ASGS_MON_LIB:-${ASGS_MON_PLUGINDIR}/_bash-helper-functions.sh}"
mon_init "$@"


mon_require_var SYSLOG
mon_require_file "$SYSLOG" SYSLOG

age=$(mon_file_age "$SYSLOG") || mon_unknown "could not determine SYSLOG age" <<EOF
SYSLOG: $SYSLOG
EOF
human=$(mon_human_age "$age")

if (( age >= 21600 )); then
    mon_warning "$human since SYSLOG updated" <<EOF
$SYSLOG

Suggested Remedy:
Log into ${HPCENV:-the ASGS host} and make sure ASGS is still progressing.

System : ${HPCENV:-}
ASGS   : ${SCRIPTDIR:-}
Profile: $PROFILE
EOF
fi

mon_verbose "($HPCENVSHORT $COLORED_PROFILE - ${GR}$THIS${R}) SYSLOG has not been updated in $human"
mon_ok "$age"
