#!/usr/bin/env bash
#--------------------------------------------------------------------------
# 004-instance-status-progress
#--------------------------------------------------------------------------
# Copyright(C) 2024-present Brett Estrade
# Copyright(C) 2024-present Jason Fleming
#
# This file is part of the ADCIRC Surge Guidance System (ASGS).
#--------------------------------------------------------------------------

source "${ASGS_MON_LIB:-${ASGS_MON_PLUGINDIR}/_bash-helper-functions.sh}"
mon_init "$@"


mon_require_var INSTANCEFILE
mon_require_file "$INSTANCEFILE" INSTANCEFILE

age=$(mon_file_age "$INSTANCEFILE") || mon_unknown "could not determine INSTANCEFILE age" <<EOF
INSTANCEFILE: $INSTANCEFILE
EOF
human=$(mon_human_age "$age")

if (( age >= 21600 )); then
    mon_warning "$human since INSTANCEFILE updated" <<EOF
$INSTANCEFILE

Suggested Remedy:
Log into ${HPCENV:-the ASGS host} and make sure ASGS is still progressing.

System : ${HPCENV:-}
ASGS   : ${SCRIPTDIR:-}
Profile: $PROFILE
EOF
fi

mon_verbose "($HPCENVSHORT $COLORED_PROFILE - ${GR}$THIS${R}) INSTANCEFILE no change in $human"
mon_ok "$age"
