#!/usr/bin/env bash
#--------------------------------------------------------------------------
# 006-rundir-du
#--------------------------------------------------------------------------
# Copyright(C) 2024-present Brett Estrade
# Copyright(C) 2024-present Jason Fleming
#
# This file is part of the ADCIRC Surge Guidance System (ASGS).
#--------------------------------------------------------------------------

source "${ASGS_MON_LIB:-${ASGS_MON_PLUGINDIR}/_bash-helper-functions.sh}"
mon_init "$@"


mon_every 5
mon_require_var RUNDIR
mon_require_dir "$RUNDIR" RUNDIR

raw_kib=$(du -sk -- "$RUNDIR" 2>/dev/null | awk 'END {print $1}')
human=$(du -sh -- "$RUNDIR" 2>/dev/null | awk 'END {print $1}')

if ! [[ "$raw_kib" =~ ^[0-9]+$ ]]; then
    mon_unknown "unable to determine RUNDIR disk usage" <<EOF
RUNDIR: $RUNDIR
EOF
fi

delta="--"
if [[ "${OLDOUT:-}" =~ ^[0-9]+$ ]]; then
    delta=$(( raw_kib - OLDOUT ))
fi

mon_verbose "($HPCENVSHORT $COLORED_PROFILE - ${GR}$THIS${R}) ${YW}RUNDIR is using ${B}${human:-?}${R}, delta ${delta} KiB"
mon_ok "$raw_kib"
