#!/usr/bin/env bash
#--------------------------------------------------------------------------
# 008-heart-beat
#--------------------------------------------------------------------------
# Copyright(C) 2024-present Brett Estrade
# Copyright(C) 2024-present Jason Fleming
#
# This file is part of the ADCIRC Surge Guidance System (ASGS).
#--------------------------------------------------------------------------

source "${ASGS_MON_LIB:-${ASGS_MON_PLUGINDIR}/_bash-helper-functions.sh}"
mon_init "$@"


now=$(date +%s)
interval=10800
next=""

if [[ "${OLDOUT:-}" =~ next[[:space:]]check[[:space:]]at[[:space:]]([0-9]+) ]]; then
    next=${BASH_REMATCH[1]}
elif [[ "${OLDOUT:-}" =~ ^[0-9]+$ ]]; then
    next=$OLDOUT
fi

if [[ -z "$next" ]]; then
    next=$(( now + interval ))
fi

if (( now >= next )); then
    next=$(( now + interval ))
    mon_notify "heartbeat; next check at $next" <<EOF
This is a periodic heartbeat confirming that asgs-mon is still running.

System  : ${HPCENV:-}
ASGS    : ${SCRIPTDIR:-}
Profile : $PROFILE
Config  : $CONFIGFILE
ASGS PID: ${ASGS_PID:-}
EOF
fi

remaining=$(( next - now ))
mon_verbose "($HPCENVSHORT $COLORED_PROFILE - ${GR}$THIS${R}) heartbeat next check at $next (${remaining}s)"
mon_ok "$next"
