#!/usr/bin/env bash
#--------------------------------------------------------------------------
# 009-syslog-scan
#--------------------------------------------------------------------------
# Copyright(C) 2024-present Brett Estrade
# Copyright(C) 2024-present Jason Fleming
#
# This file is part of the ADCIRC Surge Guidance System (ASGS).
#--------------------------------------------------------------------------

source "${ASGS_MON_LIB:-${ASGS_MON_PLUGINDIR}/_bash-helper-functions.sh}"
mon_init "$@"


mon_require_var SYSLOG
mon_require_file "$SYSLOG" SYSLOG

previous=${OLDOUT:-0}
[[ "$previous" =~ ^[0-9]+$ ]] || previous=0
current=$(wc -l < "$SYSLOG" 2>/dev/null | tr -d '[:space:]')
[[ "$current" =~ ^[0-9]+$ ]] || current=0

if (( current < previous )); then
    mon_verbose "($HPCENVSHORT $COLORED_PROFILE - ${YW}$THIS${R}) SYSLOG was truncated/rotated ($previous -> $current lines)"
    if [[ "$VERBOSE" == 1 && "$current" -gt 0 ]]; then
        tail -n 50 -- "$SYSLOG" >&2
    fi
elif (( current > previous )); then
    chunk=$(( current - previous ))
    mon_verbose "($HPCENVSHORT $COLORED_PROFILE - ${GR}$THIS${R}) SYSLOG changed by $chunk line(s):"
    if [[ "$VERBOSE" == 1 ]]; then
        if (( chunk > 200 )); then
            printf '  (showing the last 200 of %d new lines)\n' "$chunk" >&2
            tail -n 200 -- "$SYSLOG" >&2
        else
            tail -n "$chunk" -- "$SYSLOG" >&2
        fi
    fi
else
    mon_verbose "($HPCENVSHORT $COLORED_PROFILE - ${GR}$THIS${R}) SYSLOG no change, last line seen:"
    if [[ "$VERBOSE" == 1 && "$current" -gt 0 ]]; then
        tail -n 1 -- "$SYSLOG" >&2
    fi
fi

mon_ok "$current"
