#!/usr/bin/env bash
#--------------------------------------------------------------------------
# 010-STATEFILE
#--------------------------------------------------------------------------
# Copyright(C) 2024-present Brett Estrade
# Copyright(C) 2024-present Jason Fleming
#
# This file is part of the ADCIRC Surge Guidance System (ASGS).
#--------------------------------------------------------------------------

source "${ASGS_MON_LIB:-${ASGS_MON_PLUGINDIR}/_bash-helper-functions.sh}"
mon_init "$@"


mon_every 5

if [[ -z "${STATEFILE:-}" || ! -r "$STATEFILE" ]]; then
    mon_warning "STATEFILE is not readable" <<EOF
Expected state file: ${STATEFILE:-<undefined>}

The profile is loaded, but its runtime state is not currently available.
If ASGS has only just started this may be transient.
EOF
fi

if [[ -z "${RUNDIR:-}" ]]; then
    mon_warning "STATEFILE does not provide RUNDIR" <<EOF
STATEFILE: $STATEFILE
EOF
fi

display_advisory=${ADVISORY:-initialize}
[[ -z "$display_advisory" || "$display_advisory" == 0 ]] && display_advisory=initialize

mon_verbose "($HPCENVSHORT $COLORED_PROFILE - ${GR}$THIS${R}) Current Run STATES:"
mon_verbose "($HPCENVSHORT $COLORED_PROFILE - ${GR}$THIS${R}) - ${B}${YW}RUNDIR${R}   : $RUNDIR"
mon_verbose "($HPCENVSHORT $COLORED_PROFILE - ${GR}$THIS${R}) - ${B}${YW}ADVISORY${R} : $display_advisory"

mon_ok "1"
