#!/usr/bin/env bash
#--------------------------------------------------------------------------
# 999-notify-test
#--------------------------------------------------------------------------
# Copyright(C) 2024-present Brett Estrade
# Copyright(C) 2024-present Jason Fleming
#
# This file is part of the ADCIRC Surge Guidance System (ASGS).
#--------------------------------------------------------------------------

source "${ASGS_MON_LIB:-${ASGS_MON_PLUGINDIR}/_bash-helper-functions.sh}"
mon_init "$@"


tmp=${ASGS_TMPDIR:-${TMPDIR:-/tmp}}
if [[ -e "$tmp/.notify" ]]; then
    mon_notify "test notify notification requested" <<EOF
Marker file exists:
  $tmp/.notify

Remove it to stop this test condition.
EOF
fi
mon_ok "0"
