#!/usr/bin/env bash
#--------------------------------------------------------------------------
# 999-critical-test
#--------------------------------------------------------------------------
# Copyright(C) 2024-present Brett Estrade
# Copyright(C) 2024-present Jason Fleming
#
# This file is part of the ADCIRC Surge Guidance System (ASGS).
#--------------------------------------------------------------------------

source "${ASGS_MON_LIB:-${ASGS_MON_PLUGINDIR}/_bash-helper-functions.sh}"
mon_init "$@"


tmp=${ASGS_TMPDIR:-${TMPDIR:-/tmp}}
if [[ -e "$tmp/.critical" ]]; then
    mon_critical "test critical notification requested" <<EOF
Marker file exists:
  $tmp/.critical

Remove it to stop this test condition.
EOF
fi
mon_ok "0"
